### ISSUE TITLE
Your code is error when gpu0bs=0

### ISSUE THREAD

**Issue by Vast-Stars** [Link-Li/Balanced-DataParallel#3]
When gpu0bs=0, your code will definitely meet an error, but the official one will not.
Please see  data_parallel_my.py#L69-L71:
```
        replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
        if self.gpu0_bsz == 0:
            replicas = replicas[1:]
```
this will result `replicas` is 1 smaller than we need.

**Comment by Link-Li** [comment]
I upload the “data_parallel_my_v2”，it may fix the problem
