### ISSUE TITLE
关于batchsize=1

### ISSUE THREAD

**Issue by Lillian9707** [Link-Li/Balanced-DataParallel#4]
您好，我想问一下，我用balanceddataparallel并行训练后，想实时进行batchsize=1的推断行为，这个函数会报错，想问下您知道怎么解决吗？谢谢～

**Comment by Link-Li** [comment]
gpu0_bsz这个参数设置为1，在batchsize设置为1的时候

**Comment by Lillian9707** [comment]
好的 已经解决了 谢谢！
