### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by yangjianxin1** [Link-Li/Balanced-DataParallel#6]
batch_size = 32的时候，报了错，好像跟模型输入有关，没想通哪里错了
model = BalancedDataParallel(8, model, dim=0).cuda()

Traceback (most recent call last):
  File "train.py", line 580, in <module>
    main()
  File "train.py", line 576, in main
    train(model, logger, device, multi_gpu, pad_idx, train_dataset, validate_dataset, args)
  File "train.py", line 423, in train
    pad_idx=pad_idx, args=args)
  File "train.py", line 290, in train_epoch
    keyword_ids=keyword_ids)
  File "/home/workspace/data_parallel.py", line 63, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, device_ids)
  File "/home/workspace/data_parallel.py", line 88, in scatter
    bsz = inputs[0].size(self.dim)
IndexError: tuple index out of range

**Comment by Link-Li** [comment]
看看是不是dim参数设定错了，看看是不是按我说明输入的

**Comment by Tonyboy999** [comment]
一样的问题，dim用的默认0

**Comment by zhangyqCS** [comment]
> 一样的问题，dim用的默认0

请问你解决了吗？我也遇到了同样的问题

**Comment by zhangyqCS** [comment]
> batch_size = 32的时候，报了错，好像跟模型输入有关，没想通哪里错了 model = BalancedDataParallel(8, model, dim=0).cuda()
> 
> Traceback (most recent call last): File "train.py", line 580, in main() File "train.py", line 576, in main train(model, logger, device, multi_gpu, pad_idx, train_dataset, validate_dataset, args) File "train.py", line 423, in train pad_idx=pad_idx, args=args) File "train.py", line 290, in train_epoch keyword_ids=keyword_ids) File "/home/workspace/data_parallel.py", line 63, in forward inputs, kwargs = self.scatter(inputs, kwargs, device_ids) File "/home/workspace/data_parallel.py", line 88, in scatter bsz = inputs[0].size(self.dim) IndexError: tuple index out of range

请问你解决了吗？我也遇到了同样的问题
