### ISSUE TITLE
inputs is empty

### ISSUE THREAD

**Issue by tigerccx** [Link-Li/Balanced-DataParallel#7]
I am trying to run the model with `BalancedDataParallel` and I initialized my network with
 `tt = TT(args, device).to(device);
 if ((not args.cpu) and (args.num_gpu > 1)):
        tt = BalancedDataParallel(1 ,tt, dim=0);`. 

But I keep getting this error: 
`data_parallel_my.py", line 79, in scatter
    bsz = inputs[0].size(self.dim)
IndexError: tuple index out of range`

I printed `inputs` out and found it to be empty. My code works with `DataParallel ` itself so I am not sure what went wrong. Here is where I try to call the network: `srhd, S, T_lv3, T_lv2, T_lv1 = tt(lr=sr, ref=ref)`

**Comment by Link-Li** [comment]
I can not find any error juse through your code here，maybe you can make some debug to find solution.
